if(NOT DEFINED akt_all_included)
set(akt_all_included)
set(AKT_DIR ${CMAKE_CURRENT_LIST_DIR})
include(${AKT_DIR}/show_var.cmake)
include(${AKT_DIR}/message.cmake)
include(${AKT_DIR}/add_executable.cmake)
include(${AKT_DIR}/add_library.cmake)
include(${AKT_DIR}/config_version.cmake)
include(${AKT_DIR}/get_rel_subdirs.cmake)
include(${AKT_DIR}/single_scheme_add_targets_in.cmake)

else()
endif()
