if(NOT DEFINED akt_all_included)
set(akt_all_included)
set(AKT_DIR ${CMAKE_CURRENT_LIST_DIR})
include(${AKT_DIR}/show_var.cmake)
include(${AKT_DIR}/add_executable.cmake)
include(${AKT_DIR}/add_library.cmake)
include(${AKT_DIR}/config_version.cmake)

else()
endif()
