if(NOT DEFINED akt_all_included)
set(akt_all_included)
set(AKT_DIR ${CMAKE_CURRENT_LIST_DIR})
include(${AKT_DIR}/show_var.cmake)
include(${AKT_DIR}/message.cmake)
include(${AKT_DIR}/add_executable.cmake)
include(${AKT_DIR}/add_library.cmake)
include(${AKT_DIR}/config_version.cmake)
include(${AKT_DIR}/get_filename_component.cmake)
include(${AKT_DIR}/get_rel_subdirs.cmake)
include(${AKT_DIR}/target_name.cmake)
include(${AKT_DIR}/collect_srcs_and_targets.cmake)
include(${AKT_DIR}/add_targets_in.cmake)
include(${AKT_DIR}/get_debugger.cmake)
include(${AKT_DIR}/hunter/get_install_root.cmake)
include(${AKT_DIR}/vscode/gen_c_cpp_properties.cmake)
include(${AKT_DIR}/vscode/add_to_launch.cmake)
include(${AKT_DIR}/vscode/gen_launch.cmake)
include(${AKT_DIR}/cmake_package.cmake)
include(${AKT_DIR}/exclude_targets_in.cmake)
include(${AKT_DIR}/cmake_based_add_targets_in.cmake)
include(${AKT_DIR}/src_based_add_targets_in.cmake)
else()
endif()
